//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.CapaData.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_geneticaEntities : DbContext
    {
        public bd_geneticaEntities()
            : base("name=bd_geneticaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Clase> Clase { get; set; }
        public virtual DbSet<Conformacion> Conformacion { get; set; }
        public virtual DbSet<Dominio> Dominio { get; set; }
        public virtual DbSet<Especie> Especie { get; set; }
        public virtual DbSet<Familia> Familia { get; set; }
        public virtual DbSet<Filo> Filo { get; set; }
        public virtual DbSet<Gen> Gen { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<MetodoDeSecuenciacion> MetodoDeSecuenciacion { get; set; }
        public virtual DbSet<Orden> Orden { get; set; }
        public virtual DbSet<Organela> Organela { get; set; }
        public virtual DbSet<Pais> Pais { get; set; }
        public virtual DbSet<Publicacion> Publicacion { get; set; }
        public virtual DbSet<Reino> Reino { get; set; }
        public virtual DbSet<Revista_Cientifica> Revista_Cientifica { get; set; }
        public virtual DbSet<SecuenciaDeNucleotidos> SecuenciaDeNucleotidos { get; set; }
        public virtual DbSet<Titulo> Titulo { get; set; }
        public virtual DbSet<VincularArchivos> VincularArchivos { get; set; }
        public virtual DbSet<Publicacion_Archivo> Publicacion_Archivo { get; set; }
        public virtual DbSet<VistaPublicacionArchivos_FT> VistaPublicacionArchivos_FT { get; set; }
    }
}
