//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaPresentacion.CapaData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VincularArchivos
    {
        public int ID { get; set; }
        public int OtherEntityID { get; set; }
        public string DocumentID { get; set; }
        public System.DateTime InsertDT { get; set; }
        public Nullable<System.DateTime> UpdateDT { get; set; }
        public string InsertedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}
